version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  auth:
    build: ./auth-service
    ports: 
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}/${POSTGRES_DB}

  subscription::
    build: ./subscription-service
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}/${POSTGRES_DB}
    
  usage:
    build: ./usage-tracker-service
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}/${POSTGRES_DB}




